POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hellas",
    "password": "FinishXQC",
    "name": "Arto Hellas"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "IrukaiSensei",
    "password": "xqcL",
    "name": "Matti Luukainen"
}