POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
    "title": "FullStackOpen",
    "author": "Finish",
    "url": "wwwWhatever",
    "likes": 78
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IklydWthaVNlbnNlaSIsImlkIjoiNjQxZWM2NTNiZDEwNGVhMDk3ODU5ODdiIiwiaWF0IjoxNjc5NzM4ODMxfQ.wPacrptMPjo1b1J9_YXWdFO8ZdiTK6HvrWt73NpJKpA

{
    "title": "YYYawJames",
    "author": "FullStackss",
    "url": "wwwWhatever2",
    "likes": 78156
}