POST http://localhost:3001/api/persons 
Content-Type: application/json

{
      "name": "Adam", 
      "number": "010-123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
      "name": "Liisa Marttinen",
      "number": "040-243563"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
      "name": "Negi", 
      "number": "012-923456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
      "number": "012-923456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{       
    "name": "Alex"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "name": "Ar", 
      "number": "040-123456"
}